version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: backstage-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
